name: Product return
description: Used to help direct merchants to returns page.
keywords:
- Arrow
- Assist
- Exchange
- Product return
- Refund
- Return
- Return page
- Shipping
- Support
authors:
- Clara Petit
- Joe Thomas
- John Finley
date_added: 2020-07-08
date_modified: 2023-06-23
