name: Product add
description: Used as an action to add a new product.
keywords:
- Add
- Cart
- Create
- Input
- New
- Plus
- Price tag
- Product
- Shopping
authors:
- Anthony Menecola
- Joe Thomas
- John Finley
date_added: 2019-03-15
date_modified: 2023-06-23
