name: Product reference
description: Used to represent products referenced on other resources
keywords:
- Catalog
- Chain
- Connection
- Item
- Link
- Metafields
- Products
- Reference
- Symbol
authors:
- Joe Thomas
- John Finley
- Leina Leung
- Sai Nihas
date_added: 2023-01-12
date_modified: 2023-06-23
