name: Product list
description: Used to represent a list of products.
keywords:
- Collection
- Display
- Inventory
- List
- Organize
- Price
- Products
- Shopping
- Tag
authors:
- Joe Thomas
- John Finley
- Wanita Jana
date_added: 2024-01-29
date_modified: 2024-03-03
