name: Product remove
description: Used to represent an action to remove a product.
keywords:
- Basket
- Cart
- Delete
- Item
- Minus
- Product
- Remove
- Trash
authors:
- Anthony Menecola
- Joe Thomas
- John Finley
date_added: 2019-03-15
date_modified: 2023-06-23
