name: Settings
description: Used to represent settings or a configuration option.
keywords:
- Adjustments
- Cog
- Configure
- Control
- Gear
- Options
- Preferences
- Settings
authors:
- Adam Whitcroft
- Joe Thomas
- John Finley
date_added: 2019-03-15
date_modified: 2023-06-23
